baseURL = "https://blog.najamsk.now.sh"
disqusShortname = "hugo-blog-2"
highlight = false
languageCode = "en-us"
theme = "hyde-najam"
title = "Najam Sikander Awan"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1
[params]
centerTheme = false
contentTypeName = "posts"
fullWidthTheme = false
highlightjs = true
highlightjsstyle = "github"
showLanguageSelector = false
showMenuItems = 2
showcomments = true
themeColor = "orange"
[params.social]
facebook = "najams"
github = "najamsk"
instagram = "last_bubloo"
linkedin = "najamsikander"
twitter = "najamsikander"
